openapi: 3.0.0
info:
  title: Test user sign up service
  description: Test user sign up service
  version: 1.0.0

servers:
  - url: https://localhost:8080/
    description: This is where my api is

tags:
  - name: "sign up"
    description: test user sign up
paths:
  /v1/users:
    post:
      tags:
        - "sign up"
      summary: New user sign up
      description: New user sign up
      operationId: signUpNewUser
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        "201":
          description: Created
          content:
            application/json:
              schema:
                type: string
        400:
          description: Bad Request
  /v1/users/{id}:
    get:
      tags:
        - "sign up"
      summary: Get user Id
      description: Get user details
      operationId: getUserById
      parameters:
        - name: id
          in: path
          description: registerred user id
          required: true
          schema:
            type: string
      responses:
        200:
          description: Found user
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        404:
          description: user not found
        400:
          description: Bad Request
components:
  schemas:
    User:
      type: object
      required:
        - email
        - first_name
        - last_name
        - instagram_username
        - twitter_username
        - development_environment
      properties:
        id:
          type: string
          format: uuid
          readOnly: true
        email:
          type: string
          format: email
          minLength: 6
          maxLength: 100
          example: anath04jgec@gmail.com
        registered_at:
          type: string
          format: date-time
          readOnly: true
        first_name:
          type: string
          minLength: 1
          maxLength: 100
          example: John
        last_name:
          type: string
          minLength: 1
          maxLength: 100
          example: Lenon
        instagram_username:
          type: string
          minLength: 1
          maxLength: 100
          example: john_lenon
        twitter_username:
          type: string
          minLength: 1
          maxLength: 100
          example: johnlenon
        development_environment:
          type: string
          minLength: 1
          maxLength: 100
        address:
          $ref: '#/components/schemas/Address'
    Address:
      type: object
      required:
        - city
        - state
      properties:
        city:
          type: string
          minLength: 2
          maxLength: 100
          example: Austin
        state:
          type: string
          minLength: 2
          maxLength: 2
          example: TX
